"use client";
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Program={id:string;title:string;category:string;description:string;location:string;target:number;collected:number;donors:number;status:string;tone:string;icon:string;deadline:string|null};
type Transaction={id:string;programId:string;programTitle:string;donorName:string;email:string;phone:string;message:string;anonymous:number;amount:number;fee:number;method:string;status:string;provider:string;expiresAt:string|null;createdAt:string};
type Distribution={id:string;programId:string;programTitle:string;title:string;description:string;amount:number;disbursedAt:string};
type Admin={email:string;name:string;role:string}; type Audit={id:string;adminEmail:string;action:string;entityType:string;entityId:string;details:string;createdAt:string};
type Note={id:string;transactionId:string;note:string;createdBy:string;createdAt:string}; type Media={id:string;entityType:string;entityId:string;fileName:string;contentType:string;size:number;caption:string;createdBy:string;createdAt:string;url:string};
type Notification={id:string;type:string;title:string;message:string;status:string;entityType:string;entityId:string;createdAt:string};
type Data={admin:Admin;programs:Program[];transactions:Transaction[];disbursements:Distribution[];admins:Admin[];audits:Audit[];notes:Note[];media:Media[];settings:Record<string,string>;notifications:Notification[]};
type Modal="program"|"distribution"|"admin"|"transaction"|"media"|null;
const money=(value:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value);
const roleLabel:Record<string,string>={super_admin:"Super Admin",program_admin:"Admin Program",finance_admin:"Admin Keuangan",auditor:"Auditor"};
const statusLabel:Record<string,string>={pending:"Menunggu",verifying:"Verifikasi",paid:"Berhasil",failed:"Gagal",expired:"Kedaluwarsa",refunded:"Dikembalikan",draft:"Draf",published:"Terbit",paused:"Dijeda",completed:"Selesai",archived:"Diarsipkan"};
const tabNames:Record<string,string>={ringkasan:"Ringkasan hari ini",program:"Program",transaksi:"Transaksi",penyaluran:"Penyaluran",media:"Media & Dokumen",tim:"Tim & Peran",laporan:"Laporan Keuangan",pengaturan:"Pengaturan Yayasan",audit:"Jejak Audit"};

export default function AdminDashboard(){
  const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState("ringkasan"),[filter,setFilter]=useState("semua"),[search,setSearch]=useState(""),[page,setPage]=useState(1);
  const [modal,setModal]=useState<Modal>(null),[editingProgram,setEditingProgram]=useState<Program|null>(null),[editingAdmin,setEditingAdmin]=useState<Admin|null>(null),[selectedTx,setSelectedTx]=useState<Transaction|null>(null),[mediaTarget,setMediaTarget]=useState<{type:string;id:string}|null>(null);
  const [notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState("");
  const load=async()=>{setError("");try{const response=await fetch("/api/admin");const json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(err){setError(err instanceof Error?err.message:"Dashboard belum dapat dimuat.")}};
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[]); useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),3200);return()=>clearTimeout(timer)},[notice]);
  const request=async(method:string,body?:Record<string,unknown>,url="/api/admin")=>{setError("");setBusy(true);try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const json=await response.json();if(!response.ok)throw new Error(json.error);await load();return json}finally{setBusy(false)}};
  const canProgram=["super_admin","program_admin"].includes(data?.admin.role||""),canFinance=["super_admin","finance_admin"].includes(data?.admin.role||""),isSuper=data?.admin.role==="super_admin";
  const stats=useMemo(()=>{const tx=data?.transactions||[],programs=data?.programs||[],distributions=data?.disbursements||[];const paid=tx.filter(t=>t.status==="paid");return{raised:programs.reduce((s,p)=>s+p.collected,0),pending:tx.filter(t=>["pending","verifying"].includes(t.status)).reduce((s,t)=>s+t.amount,0),donors:programs.reduce((s,p)=>s+p.donors,0),distributed:distributions.reduce((s,d)=>s+d.amount,0),gross:paid.reduce((s,t)=>s+t.amount,0),fees:paid.reduce((s,t)=>s+t.fee,0)}} , [data]);
  const filteredTransactions=useMemo(()=>(data?.transactions||[]).filter(t=>(filter==="semua"||t.status===filter)&&`${t.id} ${t.donorName} ${t.email} ${t.programTitle}`.toLowerCase().includes(search.toLowerCase())),[data,filter,search]);
  const pageCount=Math.max(1,Math.ceil(filteredTransactions.length/10)),pagedTransactions=filteredTransactions.slice((page-1)*10,page*10);
  const reportTransactions=useMemo(()=>(data?.transactions||[]).filter(t=>t.status==="paid"&&(!startDate||t.createdAt.slice(0,10)>=startDate)&&(!endDate||t.createdAt.slice(0,10)<=endDate)),[data,startDate,endDate]);
  const changeTab=(next:string)=>{setTab(next);setPage(1);setError("");window.requestAnimationFrame(()=>document.querySelector(".admin-main")?.scrollIntoView({behavior:"smooth",block:"start"}))};
  const openProgram=(program:Program|null)=>{setEditingProgram(program);setModal("program")}; const openAdmin=(admin:Admin|null)=>{setEditingAdmin(admin);setModal("admin")};
  const submitProgram=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{await request(editingProgram?"PATCH":"POST",{action:"program",...(editingProgram?{id:editingProgram.id}:{}),...payload,target:Number(payload.target)});setModal(null);setNotice(editingProgram?"Program diperbarui.":"Program ditambahkan.")}catch(err){setError(err instanceof Error?err.message:"Gagal menyimpan program.")}};
  const submitDistribution=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{await request("POST",{action:"disbursement",...payload,amount:Number(payload.amount)});setModal(null);setNotice("Laporan penyaluran diterbitkan.")}catch(err){setError(err instanceof Error?err.message:"Gagal mencatat penyaluran.")}};
  const submitAdmin=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{await request(editingAdmin?"PATCH":"POST",{action:"admin",...payload});setModal(null);setNotice("Akses anggota diperbarui.")}catch(err){setError(err instanceof Error?err.message:"Gagal menyimpan anggota.")}};
  const submitSettings=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();try{await request("POST",{action:"settings",...Object.fromEntries(new FormData(event.currentTarget))});setNotice("Pengaturan yayasan tersimpan.")}catch(err){setError(err instanceof Error?err.message:"Gagal menyimpan pengaturan.")}};
  const submitNote=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selectedTx)return;const form=new FormData(event.currentTarget);try{await request("POST",{action:"transaction_note",transactionId:selectedTx.id,note:form.get("note")});event.currentTarget.reset();setNotice("Catatan transaksi ditambahkan.")}catch(err){setError(err instanceof Error?err.message:"Gagal menambahkan catatan.")}};
  const submitMedia=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!mediaTarget)return;setBusy(true);setError("");try{const form=new FormData(event.currentTarget);form.set("entityType",mediaTarget.type);form.set("entityId",mediaTarget.id);const response=await fetch("/api/media",{method:"POST",body:form});const json=await response.json();if(!response.ok)throw new Error(json.error);await load();setModal(null);setNotice("Media berhasil diunggah.")}catch(err){setError(err instanceof Error?err.message:"Gagal mengunggah media.")}finally{setBusy(false)}};
  const updateStatus=async(transaction:Transaction,status:string,fee=transaction.fee)=>{try{await request("PATCH",{action:"transaction",id:transaction.id,status,fee});setNotice("Status transaksi diperbarui.")}catch(err){setError(err instanceof Error?err.message:"Gagal memperbarui transaksi.")}};
  const removeProgram=async(program:Program)=>{if(!confirm(`Arsipkan ${program.title}?`))return;try{const result=await request("DELETE",undefined,`/api/admin?type=program&id=${encodeURIComponent(program.id)}`);setNotice(result.archived?"Program diarsipkan karena memiliki transaksi.":"Program dihapus.")}catch(err){setError(err instanceof Error?err.message:"Gagal mengarsipkan program.")}};
  const removeAdmin=async(admin:Admin)=>{if(!confirm(`Hapus akses ${admin.name}?`))return;try{await request("DELETE",undefined,`/api/admin?type=admin&id=${encodeURIComponent(admin.email)}`);setNotice("Akses anggota dihapus.")}catch(err){setError(err instanceof Error?err.message:"Gagal menghapus akses.")}};
  const removeMedia=async(item:Media)=>{if(!confirm(`Hapus ${item.fileName}?`))return;try{await request("DELETE",undefined,`/api/media/${encodeURIComponent(item.id)}`);setNotice("Media dihapus.")}catch(err){setError(err instanceof Error?err.message:"Gagal menghapus media.")}};
  const download=(name:string,value:string,type:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([value],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
  const exportCsv=()=>{const rows=[["ID","Donatur","Email","Program","Nominal","Biaya","Bersih","Metode","Status","Tanggal"],...filteredTransactions.map(t=>[t.id,t.donorName,t.email,t.programTitle,String(t.amount),String(t.fee),String(t.amount-t.fee),t.method,statusLabel[t.status],t.createdAt])];download("laporan-griya-jariyah.csv",`\uFEFF${rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(",")).join("\n")}`,"text/csv")};
  const backup=async()=>{setBusy(true);try{const response=await fetch("/api/admin?backup=1");const json=await response.json();if(!response.ok)throw new Error(json.error);download(`backup-griya-jariyah-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(json,null,2),"application/json");setNotice("Backup berhasil diunduh.")}catch(err){setError(err instanceof Error?err.message:"Backup gagal.")}finally{setBusy(false)}};
  if(!data)return <main className="admin-loading"><div className="brand"><span className="brand-mark">G</span><span>Griya Jariyah <span>Nurul Iman</span></span></div><p>{error||"Menyiapkan dashboard aman…"}</p>{error&&<Link href="/">Kembali ke beranda</Link>}</main>;
  const menu=[["ringkasan","⌂","Ringkasan"],["program","✦","Program"],["transaksi","▤","Transaksi"],["penyaluran","↗","Penyaluran"],["media","▣","Media"],["tim","♙","Tim & Peran"],["laporan","▥","Laporan"],["pengaturan","⚙","Pengaturan"],["audit","◷","Audit"]];
  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="brand inverse" href="/"><span className="brand-mark">G</span><span>Griya Jariyah <span>Nurul Iman</span></span></Link><nav aria-label="Menu dashboard">{menu.map(([id,icon,label])=><button type="button" key={id} aria-pressed={tab===id} className={tab===id?"active":""} onClick={()=>changeTab(id)}><span>{icon}</span>{label}</button>)}</nav><div className="admin-account"><div>{data.admin.name.charAt(0)}</div><p><strong>{data.admin.name}</strong><span>{roleLabel[data.admin.role]}</span></p><a aria-label="Keluar" href="/signout-with-chatgpt?return_to=/">↗</a></div></aside>
  <section className="admin-main" aria-live="polite"><header><div><span className="section-kicker">Dashboard Yayasan</span><h1>{tabNames[tab]}</h1></div><div className="header-actions"><button onClick={()=>changeTab("ringkasan")} className="notification-button">● <span>{data.notifications.filter(n=>n.status==="unread").length}</span></button><a href="/" target="_blank" rel="noreferrer">Lihat situs ↗</a></div></header>{error&&<div className="admin-alert">{error}<button onClick={()=>setError("")}>×</button></div>}
  {tab==="ringkasan"&&<><div className="admin-stats"><article><span>↗</span><p>Total dana<strong>{money(stats.raised)}</strong><small>Terverifikasi</small></p></article><article><span>◷</span><p>Menunggu<strong>{money(stats.pending)}</strong><small>Perlu ditindaklanjuti</small></p></article><article><span>♙</span><p>Donatur<strong>{stats.donors.toLocaleString("id-ID")}</strong><small>Seluruh program</small></p></article><article><span>✓</span><p>Tersalurkan<strong>{money(stats.distributed)}</strong><small>Dilaporkan publik</small></p></article></div><div className="admin-overview"><section className="admin-card"><div className="admin-card-title"><div><h2>Performa program</h2><p>Progres penggalangan dana aktif.</p></div>{canProgram&&<button onClick={()=>openProgram(null)}>＋ Program</button>}</div>{data.programs.slice(0,5).map(p=><div className="overview-program" key={p.id}><div className={`program-thumb ${p.tone}`}>{p.icon}</div><p><strong>{p.title}</strong><span>{money(p.collected)} dari {money(p.target)}</span><i><b style={{width:`${Math.min(100,p.collected/p.target*100)}%`}}></b></i></p><em>{Math.round(p.collected/p.target*100)}%</em></div>)}</section><section className="admin-card"><div className="admin-card-title"><div><h2>Pusat notifikasi</h2><p>Aktivitas yang perlu diperhatikan.</p></div></div>{data.notifications.slice(0,6).map(n=><button className={`notification-item ${n.status}`} key={n.id} onClick={async()=>{if(n.status==="unread")await request("PATCH",{action:"notification",id:n.id})}}><span>{n.type==="target"?"◎":"◷"}</span><div><strong>{n.title}</strong><small>{n.message}</small></div></button>)}{!data.notifications.length&&<div className="empty-admin">Belum ada notifikasi.</div>}</section></div></>}
  {tab==="program"&&<section className="admin-card full-card"><div className="admin-card-title"><div><h2>Semua program</h2><p>Kelola status, target, isi, dan dokumentasi program.</p></div>{canProgram&&<button onClick={()=>openProgram(null)}>＋ Tambah program</button>}</div><div className="data-table"><div className="table-head"><span>Program</span><span>Status</span><span>Progres</span><span>Target</span><span>Aksi</span></div>{data.programs.map(p=><div className="table-row" key={p.id}><span><strong>{p.title}</strong><small>{p.category} · {p.location}</small></span><span><b className={`status ${p.status}`}>{statusLabel[p.status]}</b></span><span>{Math.round(p.collected/p.target*100)}% · {p.donors} donatur</span><span>{money(p.target)}</span><span className="row-actions">{canProgram&&<button onClick={()=>openProgram(p)}>Edit</button>}{canProgram&&<button onClick={()=>{setMediaTarget({type:"program",id:p.id});setModal("media")}}>Media</button>}{isSuper&&<button onClick={()=>removeProgram(p)}>Arsip</button>}</span></div>)}</div></section>}
  {tab==="transaksi"&&<section className="admin-card full-card"><div className="admin-card-title"><div><h2>Semua transaksi</h2><p>Cari, verifikasi, rekonsiliasi, dan periksa detail transaksi.</p></div><button onClick={exportCsv}>↓ Ekspor CSV</button></div><div className="table-tools"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Cari ID, donatur, email, atau program…"/><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="semua">Semua status</option>{["pending","verifying","paid","failed","expired","refunded"].map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></div><div className="data-table transactions-table"><div className="table-head"><span>Donatur</span><span>Program</span><span>Nominal</span><span>Status</span><span>Aksi</span></div>{pagedTransactions.map(t=><div className="table-row" key={t.id}><span><strong>{t.donorName}</strong><small>{t.id} · {t.email}</small></span><span>{t.programTitle}<small>{t.method} · {t.provider}</small></span><span>{money(t.amount)}<small>Bersih {money(t.amount-t.fee)}</small></span><span><b className={`status ${t.status}`}>{statusLabel[t.status]}</b></span><span className="row-actions"><button onClick={()=>{setSelectedTx(t);setModal("transaction")}}>Detail</button>{canFinance&&t.status!=="paid"&&<button onClick={()=>updateStatus(t,"paid")}>Verifikasi</button>}</span></div>)}</div><div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Sebelumnya</button><span>Halaman {page} dari {pageCount}</span><button disabled={page>=pageCount} onClick={()=>setPage(p=>p+1)}>Berikutnya →</button></div></section>}
  {tab==="penyaluran"&&<section className="admin-card full-card"><div className="admin-card-title"><div><h2>Laporan penyaluran</h2><p>Pembaruan ini tampil di halaman publik.</p></div>{canFinance&&<button onClick={()=>setModal("distribution")}>＋ Catat penyaluran</button>}</div><div className="distribution-list">{data.disbursements.map(d=><article key={d.id}><span>✓</span><div><strong>{d.title}</strong><p>{d.description}</p><small>{d.programTitle} · {new Date(d.disbursedAt).toLocaleDateString("id-ID")}</small>{canFinance&&<button className="inline-action" onClick={()=>{setMediaTarget({type:"disbursement",id:d.id});setModal("media")}}>＋ Dokumentasi</button>}</div><b>{money(d.amount)}</b></article>)}</div></section>}
  {tab==="media"&&<section className="admin-card full-card"><div className="admin-card-title"><div><h2>Media dan dokumen</h2><p>Foto program, dokumentasi penyaluran, dan bukti PDF.</p></div>{(canProgram||canFinance)&&<button onClick={()=>{setMediaTarget(canProgram?{type:"program",id:data.programs[0]?.id||""}:{type:"disbursement",id:data.disbursements[0]?.id||""});setModal("media")}}>＋ Unggah media</button>}</div><div className="media-grid">{data.media.map(item=><article key={item.id}>{item.contentType.startsWith("image/")?<img src={item.url} alt={item.caption||item.fileName}/>:<a className="pdf-card" href={item.url} target="_blank" rel="noreferrer">PDF</a>}<div><strong>{item.caption||item.fileName}</strong><small>{item.entityType} · {(item.size/1024).toFixed(0)} KB</small></div>{(isSuper||(canProgram&&item.entityType==="program")||(canFinance&&item.entityType==="disbursement"))&&<button onClick={()=>removeMedia(item)}>×</button>}</article>)}{!data.media.length&&<div className="empty-admin">Belum ada media. Unggah foto atau bukti penyaluran pertama.</div>}</div></section>}
  {tab==="tim"&&<section className="admin-card full-card"><div className="admin-card-title"><div><h2>Tim dan peran</h2><p>Atur batas akses setiap anggota yayasan.</p></div>{isSuper&&<button onClick={()=>openAdmin(null)}>＋ Tambah anggota</button>}</div><div className="team-grid">{data.admins.map(a=><article key={a.email}><span>{a.name.charAt(0)}</span><div><strong>{a.name}</strong><p>{a.email}</p><small>{roleLabel[a.role]}</small>{isSuper&&<div className="team-actions"><button onClick={()=>openAdmin(a)}>Edit</button>{a.email!==data.admin.email&&<button onClick={()=>removeAdmin(a)}>Hapus</button>}</div>}</div></article>)}</div></section>}
  {tab==="laporan"&&<section className="admin-card full-card report-card"><div className="admin-card-title"><div><h2>Laporan dan rekonsiliasi</h2><p>Ringkasan pembayaran berhasil dan dana bersih.</p></div><div><button onClick={()=>window.print()}>Cetak / PDF</button><button onClick={exportCsv}>CSV</button><button onClick={backup} disabled={busy}>Backup JSON</button></div></div><div className="report-filters"><label>Dari<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>Sampai<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div><div className="reconcile-grid"><article><small>Dana bruto</small><strong>{money(reportTransactions.reduce((s,t)=>s+t.amount,0))}</strong></article><article><small>Biaya layanan</small><strong>{money(reportTransactions.reduce((s,t)=>s+t.fee,0))}</strong></article><article><small>Dana bersih</small><strong>{money(reportTransactions.reduce((s,t)=>s+t.amount-t.fee,0))}</strong></article><article><small>Sudah disalurkan</small><strong>{money(stats.distributed)}</strong></article></div><div className="data-table"><div className="table-head report-head"><span>Transaksi</span><span>Program</span><span>Bruto</span><span>Biaya</span><span>Bersih</span></div>{reportTransactions.map(t=><div className="table-row report-head" key={t.id}><span><strong>{t.id}</strong><small>{t.createdAt.slice(0,10)}</small></span><span>{t.programTitle}</span><span>{money(t.amount)}</span><span>{money(t.fee)}</span><span>{money(t.amount-t.fee)}</span></div>)}</div></section>}
  {tab==="pengaturan"&&<section className="admin-card full-card settings-card"><div className="admin-card-title"><div><h2>Identitas yayasan</h2><p>Informasi ini ditampilkan pada halaman publik dan laporan.</p></div></div><form onSubmit={submitSettings}><div className="form-row"><div><label>Nama yayasan</label><input className="field" name="organization_name" defaultValue={data.settings.organization_name}/></div><div><label>Nomor legalitas</label><input className="field" name="legal_number" defaultValue={data.settings.legal_number}/></div></div><label>Alamat</label><textarea className="field" name="address" defaultValue={data.settings.address}/><div className="form-row"><div><label>Email</label><input className="field" name="email" type="email" defaultValue={data.settings.email}/></div><div><label>Telepon / WhatsApp</label><input className="field" name="phone" defaultValue={data.settings.phone}/></div></div><div className="form-row"><div><label>Nama bank</label><input className="field" name="bank_name" defaultValue={data.settings.bank_name}/></div><div><label>Nomor rekening</label><input className="field" name="bank_account" defaultValue={data.settings.bank_account}/></div></div><label>Instagram</label><input className="field" name="instagram" defaultValue={data.settings.instagram}/>{isSuper?<button className="primary" disabled={busy}>Simpan pengaturan</button>:<p className="form-error">Hanya Super Admin yang dapat mengubah pengaturan.</p>}</form></section>}
  {tab==="audit"&&<section className="admin-card full-card"><div className="admin-card-title"><div><h2>Jejak audit</h2><p>Riwayat tindakan penting oleh pengelola.</p></div></div><div className="audit-list">{data.audits.map(a=><article key={a.id}><span>◷</span><div><strong>{a.adminEmail}</strong><p>{a.action} {a.entityType} · {a.details||a.entityId}</p><small>{new Date(a.createdAt+"Z").toLocaleString("id-ID")}</small></div></article>)}</div></section>}
  </section>

  {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className="modal compact"><button className="modal-close" onClick={()=>setModal(null)}>×</button>
    {modal==="program"&&<><span className="section-kicker">{editingProgram?"Edit Program":"Program Baru"}</span><h2>{editingProgram?"Perbarui program.":"Mulai gerakan baik."}</h2><form onSubmit={submitProgram}><label>Nama program</label><input className="field" name="title" defaultValue={editingProgram?.title} required/><div className="form-row"><div><label>Kategori</label><select className="field" name="category" defaultValue={editingProgram?.category||"Kemanusiaan"}>{["Kemanusiaan","Pendidikan","Kesehatan","Lingkungan","Keagamaan"].map(v=><option key={v}>{v}</option>)}</select></div><div><label>Lokasi</label><input className="field" name="location" defaultValue={editingProgram?.location||"Indonesia"} required/></div></div><label>Deskripsi</label><textarea className="field" name="description" defaultValue={editingProgram?.description} required/><div className="form-row"><div><label>Target dana</label><input className="field" name="target" type="number" min="100000" defaultValue={editingProgram?.target} required/></div><div><label>Tenggat</label><input className="field" name="deadline" type="date" defaultValue={editingProgram?.deadline||""}/></div></div><label>Status</label><select className="field" name="status" defaultValue={editingProgram?.status||"draft"}>{["draft","published","paused","completed","archived"].map(v=><option key={v} value={v}>{statusLabel[v]}</option>)}</select><input type="hidden" name="tone" value={editingProgram?.tone||"rose"}/><input type="hidden" name="icon" value={editingProgram?.icon||"✦"}/><button className="primary full" disabled={busy}>Simpan program</button></form></>}
    {modal==="distribution"&&<><span className="section-kicker">Laporan Publik</span><h2>Catat penyaluran.</h2><form onSubmit={submitDistribution}><label>Program</label><select className="field" name="programId">{data.programs.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select><label>Judul kegiatan</label><input className="field" name="title" required/><label>Deskripsi</label><textarea className="field" name="description" required/><div className="form-row"><div><label>Nominal</label><input className="field" name="amount" type="number" min="1" required/></div><div><label>Tanggal</label><input className="field" name="disbursedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div></div><button className="primary full" disabled={busy}>Terbitkan laporan</button></form></>}
    {modal==="admin"&&<><span className="section-kicker">Akses Tim</span><h2>{editingAdmin?"Edit pengelola.":"Tambah pengelola."}</h2><form onSubmit={submitAdmin}><label>Nama</label><input className="field" name="name" defaultValue={editingAdmin?.name} required/><label>Email akun ChatGPT</label><input className="field" name="email" type="email" defaultValue={editingAdmin?.email} readOnly={Boolean(editingAdmin)} required/><label>Peran</label><select className="field" name="role" defaultValue={editingAdmin?.role||"program_admin"}><option value="program_admin">Admin Program</option><option value="finance_admin">Admin Keuangan</option><option value="auditor">Auditor</option><option value="super_admin">Super Admin</option></select><button className="primary full" disabled={busy}>Simpan akses</button></form></>}
    {modal==="transaction"&&selectedTx&&<><span className="section-kicker">Detail Transaksi</span><h2>{selectedTx.id}</h2><div className="transaction-detail"><p><span>Donatur</span><strong>{selectedTx.donorName}</strong></p><p><span>Kontak</span><strong>{selectedTx.email}<br/>{selectedTx.phone}</strong></p><p><span>Program</span><strong>{selectedTx.programTitle}</strong></p><p><span>Nominal</span><strong>{money(selectedTx.amount)}</strong></p><p><span>Pesan</span><strong>{selectedTx.message||"—"}</strong></p></div>{canFinance&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await updateStatus(selectedTx,String(f.get("status")),Number(f.get("fee")));setModal(null)}}><div className="form-row"><div><label>Status</label><select className="field" name="status" defaultValue={selectedTx.status}>{["pending","verifying","paid","failed","expired","refunded"].map(s=><option value={s} key={s}>{statusLabel[s]}</option>)}</select></div><div><label>Biaya layanan</label><input className="field" name="fee" type="number" min="0" max={selectedTx.amount} defaultValue={selectedTx.fee}/></div></div><button className="primary full">Simpan rekonsiliasi</button></form>}<div className="notes"><h3>Catatan internal</h3>{data.notes.filter(n=>n.transactionId===selectedTx.id).map(n=><article key={n.id}><p>{n.note}</p><small>{n.createdBy} · {new Date(n.createdAt+"Z").toLocaleString("id-ID")}</small></article>)}<form onSubmit={submitNote}><textarea className="field" name="note" placeholder="Tambahkan catatan internal…" required/><button className="card-button">Tambah catatan</button></form></div></>}
    {modal==="media"&&mediaTarget&&<><span className="section-kicker">Dokumentasi</span><h2>Unggah media.</h2><form onSubmit={submitMedia}><label>Tujuan</label><select className="field" value={`${mediaTarget.type}:${mediaTarget.id}`} onChange={e=>{const [type,...rest]=e.target.value.split(":");setMediaTarget({type,id:rest.join(":")})}}>{canProgram&&<optgroup label="Program">{data.programs.map(p=><option value={`program:${p.id}`} key={p.id}>{p.title}</option>)}</optgroup>}{canFinance&&<optgroup label="Penyaluran">{data.disbursements.map(d=><option value={`disbursement:${d.id}`} key={d.id}>{d.title}</option>)}</optgroup>}</select><label>Berkas (maksimal 900 KB)</label><input className="field" name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/><label>Keterangan</label><input className="field" name="caption" placeholder="Contoh: Penyaluran tahap pertama"/><button className="primary full" disabled={busy}>{busy?"Mengunggah…":"Unggah media"}</button></form></>}
  </section></div>}{notice&&<div className="toast"><span>✓</span>{notice}</div>}</main>;
}
